using System.Collections.Generic;
using UnityEngine;

public class AssassinDeck : MonoBehaviour 
{
    public static List<CardClass> assassindeck = new List<CardClass>()
    {
        new CardClass("Backstab", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Poison Dagger", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Shadowstep", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Evasion", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Assassinate", 3, "This card does: 12 damage", CardType.Attack, 12, 0),      
        new CardClass("Smoke Bomb", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Blade Flurry", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Cloak of Shadows", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Fan of Knives", 2, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Garrote", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Quick Strike", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Vanish", 2, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Kidney Shot", 3, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Cheap Shot", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Gouge", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Shiv", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Deflect", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Shadow Strike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Feint", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Shadow Dance", 3, "This card does: 5 damage and 5 shield", CardType.Both, 5, 5),
        new CardClass("Ambush", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Riposte", 2, "This card does: 3 damage and 4 shield", CardType.Both, 3, 4),
        new CardClass("Preparation", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Sprint", 2, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Sap", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Crimson Vial", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Marked Strike", 2, "This card does: 4 damage and 3 shield", CardType.Both, 4, 3),
        new CardClass("Distract", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Execute", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Shadow Barrier", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Backstab", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Poison Dagger", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Shadowstep", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Evasion", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Assassinate", 3, "This card does: 12 damage", CardType.Attack, 12, 0),      
        new CardClass("Smoke Bomb", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Blade Flurry", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Cloak of Shadows", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Fan of Knives", 2, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Garrote", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Quick Strike", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Vanish", 2, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Kidney Shot", 3, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Cheap Shot", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Gouge", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Shiv", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Deflect", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Shadow Strike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Feint", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Shadow Dance", 3, "This card does: 5 damage and 5 shield", CardType.Both, 5, 5),
        new CardClass("Ambush", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Riposte", 2, "This card does: 3 damage and 4 shield", CardType.Both, 3, 4),
        new CardClass("Preparation", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Sprint", 2, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Sap", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Crimson Vial", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Marked Strike", 2, "This card does: 4 damage and 3 shield", CardType.Both, 4, 3),
        new CardClass("Distract", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Execute", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Shadow Barrier", 2, "This card does: 8 shield", CardType.Defense, 0, 8)
    };
}