using System.Collections.Generic;
using UnityEngine;

public class KnightDeck : MonoBehaviour 
{
    public static List<CardClass> knightdeck = new List<CardClass>()
    {
        new CardClass("Shield Bash", 2, "This card does: 4 damage and 3 shield", CardType.Both, 4, 3),
        new CardClass("Defend", 1, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Heavy Strike", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Iron Wall", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Slash", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Cleave", 3, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Battle Stance", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Power Strike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Block", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Charge", 3, "This card does: 7 damage and 2 shield", CardType.Both, 7, 2),
        new CardClass("Fortify", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Heroic Strike", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Guardian", 2, "This card does: 9 shield", CardType.Defense, 0, 9),
        new CardClass("Shield Wall", 3, "This card does: 15 shield", CardType.Defense, 0, 15),
        new CardClass("Overhead Slash", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Parry", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Crushing Blow", 3, "This card does: 12 damage", CardType.Attack, 12, 0),
        new CardClass("Stalwart Defense", 3, "This card does: 10 shield", CardType.Defense, 0, 10),
        new CardClass("Sword and Board", 3, "This card does: 5 damage and 5 shield", CardType.Both, 5, 5),
        new CardClass("Brace", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Riposte", 2, "This card does: 4 damage and 4 shield", CardType.Both, 4, 4),
        new CardClass("Mighty Blow", 2, "This card does: 7 damage", CardType.Attack, 7, 0),
        new CardClass("Armor Up", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Shield Slam", 2, "This card does: 5 damage and 3 shield", CardType.Both, 5, 3),
        new CardClass("Shockwave", 3, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Bulwark", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Execute", 2, "This card does: 9 damage", CardType.Attack, 9, 0),
        new CardClass("Steadfast", 1, "This card does: 2 shield", CardType.Defense, 0, 2),
        new CardClass("Rampage", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Valiant Defense", 3, "This card does: 9 damage and 4 shield", CardType.Both, 9, 4),
        new CardClass("Shield Bash", 2, "This card does: 4 damage and 3 shield", CardType.Both, 4, 3),
        new CardClass("Defend", 1, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Heavy Strike", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Iron Wall", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Slash", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Cleave", 3, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Battle Stance", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Power Strike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Block", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Charge", 3, "This card does: 7 damage and 2 shield", CardType.Both, 7, 2),
        new CardClass("Fortify", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Heroic Strike", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Guardian", 2, "This card does: 9 shield", CardType.Defense, 0, 9),
        new CardClass("Shield Wall", 3, "This card does: 15 shield", CardType.Defense, 0, 15),
        new CardClass("Overhead Slash", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Parry", 1, "This card does: 3 shield", CardType.Defense, 0, 3),
        new CardClass("Crushing Blow", 3, "This card does: 12 damage", CardType.Attack, 12, 0),
        new CardClass("Stalwart Defense", 3, "This card does: 10 shield", CardType.Defense, 0, 10),
        new CardClass("Sword and Board", 3, "This card does: 5 damage and 5 shield", CardType.Both, 5, 5),
        new CardClass("Brace", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Riposte", 2, "This card does: 4 damage and 4 shield", CardType.Both, 4, 4),
        new CardClass("Mighty Blow", 2, "This card does: 7 damage", CardType.Attack, 7, 0),
        new CardClass("Armor Up", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Shield Slam", 2, "This card does: 5 damage and 3 shield", CardType.Both, 5, 3),
        new CardClass("Shockwave", 3, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Bulwark", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Execute", 2, "This card does: 9 damage", CardType.Attack, 9, 0),
        new CardClass("Steadfast", 1, "This card does: 2 shield", CardType.Defense, 0, 2),
        new CardClass("Rampage", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Valiant Defense", 3, "This card does: 9 damage and 4 shield", CardType.Both, 9, 4),
    };
}