using System.Collections.Generic;
using UnityEngine;

public class MageDeck : MonoBehaviour 
{
    public static List<CardClass> magedeck = new List<CardClass>()
    {
        new CardClass("Fireball", 2, "This card does: 7 damage", CardType.Attack, 7, 0),
        new CardClass("Frost Shield", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Arcane Missiles", 1, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Mana Shield", 2, "This card does: 10 shield", CardType.Defense, 0, 10),
        new CardClass("Lightning Bolt", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Blizzard", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Ice Barrier", 1, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Ice Block", 3, "This card does: 12 shield", CardType.Defense, 0, 12),
        new CardClass("Pyroblast", 3, "This card does: 15 damage", CardType.Attack, 15, 0),
        new CardClass("Arcane Blast", 1, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Flamestrike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Magic Barrier", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Arcane Explosion", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Mirror Image", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Fire Blast", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Frostbolt", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Arcane Shield", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Meteor", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Frost Armor", 2, "This card does: 9 shield", CardType.Defense, 0, 9),
        new CardClass("Cone of Cold", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Mana Burst", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Arcane Barrage", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Ring of Frost", 2, "This card does: 5 damage and 3 shield", CardType.Both, 5, 3),
        new CardClass("Fire Shield", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Arcane Strike", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Living Bomb", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Dragon's Breath", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Glacial Armor", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Scorch", 1, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Elemental Ward", 3, "This card does: 6 damage and 6 shield", CardType.Both, 6, 6),
        new CardClass("Fireball", 2, "This card does: 7 damage", CardType.Attack, 7, 0),
        new CardClass("Frost Shield", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Arcane Missiles", 1, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Mana Shield", 2, "This card does: 10 shield", CardType.Defense, 0, 10),
        new CardClass("Lightning Bolt", 3, "This card does: 10 damage", CardType.Attack, 10, 0),
        new CardClass("Blizzard", 2, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Ice Barrier", 1, "This card does: 5 shield", CardType.Defense, 0, 5),
        new CardClass("Ice Block", 3, "This card does: 12 shield", CardType.Defense, 0, 12),
        new CardClass("Pyroblast", 3, "This card does: 15 damage", CardType.Attack, 15, 0),
        new CardClass("Arcane Blast", 1, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Flamestrike", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Magic Barrier", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Arcane Explosion", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Mirror Image", 2, "This card does: 6 shield", CardType.Defense, 0, 6),
        new CardClass("Fire Blast", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Frostbolt", 2, "This card does: 5 damage", CardType.Attack, 5, 0),
        new CardClass("Arcane Shield", 1, "This card does: 4 shield", CardType.Defense, 0, 4),
        new CardClass("Meteor", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Frost Armor", 2, "This card does: 9 shield", CardType.Defense, 0, 9),
        new CardClass("Cone of Cold", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Mana Burst", 1, "This card does: 2 damage", CardType.Attack, 2, 0),
        new CardClass("Arcane Barrage", 2, "This card does: 6 damage", CardType.Attack, 6, 0),
        new CardClass("Ring of Frost", 2, "This card does: 5 damage and 3 shield", CardType.Both, 5, 3),
        new CardClass("Fire Shield", 2, "This card does: 8 shield", CardType.Defense, 0, 8),
        new CardClass("Arcane Strike", 1, "This card does: 3 damage", CardType.Attack, 3, 0),
        new CardClass("Living Bomb", 2, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Dragon's Breath", 3, "This card does: 8 damage", CardType.Attack, 8, 0),
        new CardClass("Glacial Armor", 2, "This card does: 7 shield", CardType.Defense, 0, 7),
        new CardClass("Scorch", 1, "This card does: 4 damage", CardType.Attack, 4, 0),
        new CardClass("Elemental Ward", 3, "This card does: 6 damage and 6 shield", CardType.Both, 6, 6)
    };
}